name       : libdrm
version    : 2.4.108
release    : 36
source     :
    - https://gitlab.freedesktop.org/mesa/drm/-/archive/libdrm-2.4.108/drm-libdrm-2.4.108.tar.bz2 : 156ea2bf0df10508d73fce82c5ec25bc1c2a68499fd56e05d177a147358eaf21
license    : MIT
component  : xorg.display
summary    : Direct Rendering Manager API + Library
description: |
    libdrm provides core library routines for the X Window System to directly interface with video hardware using the Linux kernel's Direct Rendering Manager (DRM).
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(pciaccess)
    - pkgconfig(pciaccess)
    - pkgconfig(xorg-macros)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
