name        : libdrm
version     : 2.4.65
release     : 8
source     :
    - http://dri.freedesktop.org/libdrm/libdrm-2.4.65.tar.gz : b4382d6018464ba5bece2d7a4b87eb0eba24d891ff2ba29549be9511bd231c2f
license     :
    - MIT
summary     : Direct Rendering Manager API + Library
builddeps   :
    - pkgconfig32(pciaccess)
    - pkgconfig(xorg-macros)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    libdrm provides core library routines for the X Window System to directly interface with video hardware using the Linux kernel's Direct Rendering Manager (DRM).
setup      : |
    sed -e /pthread-stubs/d -i configure.ac
    autoreconf -vfi
    %configure --prefix=/usr --disable-static --enable-udev
build      : |
    %make
install    : |
    %make_install
    %make clean
