name       : libdrm
version    : 2.4.83
release    : 19
source     :
    - https://dri.freedesktop.org/libdrm/libdrm-2.4.83.tar.gz : 2ff5f626a14ec5bd680f7769cac9a8eb1e40c36cf5ca554d2c4e5d91bab3d81d
license    : MIT
component  : xorg.display
summary    : Direct Rendering Manager API + Library
description: |
    libdrm provides core library routines for the X Window System to directly interface with video hardware using the Linux kernel's Direct Rendering Manager (DRM).
builddeps  :
    - pkgconfig32(pciaccess)
    - pkgconfig(pciaccess)
    - pkgconfig(xorg-macros)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
setup      : |
    # sed -e /pthread-stubs/d -i configure.ac
    %reconfigure --prefix=/usr --disable-static --enable-udev
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
