name       : libdrm
version    : 2.4.88
release    : 20
source     :
    - https://dri.freedesktop.org/libdrm/libdrm-2.4.88.tar.gz : a8b458db6a73c717baee2e249d39511fb6f5c0f5f24dee2770935eddeda1a017
license    : MIT
component  : xorg.display
summary    : Direct Rendering Manager API + Library
description: |
    libdrm provides core library routines for the X Window System to directly interface with video hardware using the Linux kernel's Direct Rendering Manager (DRM).
builddeps  :
    - pkgconfig32(pciaccess)
    - pkgconfig(pciaccess)
    - pkgconfig(xorg-macros)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
setup      : |
    # sed -e /pthread-stubs/d -i configure.ac
    %reconfigure --prefix=/usr --disable-static --enable-udev
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
