name       : libdrm
version    : 2.4.103
release    : 32
source     :
    - https://gitlab.freedesktop.org/mesa/drm/-/archive/libdrm-2.4.103/drm-libdrm-2.4.103.tar.bz2 : c98202fe81ea08fac5e8b7e124116e364af394f68dfee4f694c71eeabd711158
license    : MIT
component  : xorg.display
summary    : Direct Rendering Manager API + Library
description: |
    libdrm provides core library routines for the X Window System to directly interface with video hardware using the Linux kernel's Direct Rendering Manager (DRM).
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(pciaccess)
    - pkgconfig(pciaccess)
    - pkgconfig(xorg-macros)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
