name       : libdrm
version    : 2.4.106
release    : 34
source     :
    - https://gitlab.freedesktop.org/mesa/drm/-/archive/libdrm-2.4.106/drm-libdrm-2.4.106.tar.bz2 : 60e7f068af3d0cbfc075be86ecccb01d34dc228b2b33cb1d06ca4feaa5c866e0
license    : MIT
component  : xorg.display
summary    : Direct Rendering Manager API + Library
description: |
    libdrm provides core library routines for the X Window System to directly interface with video hardware using the Linux kernel's Direct Rendering Manager (DRM).
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(pciaccess)
    - pkgconfig(pciaccess)
    - pkgconfig(xorg-macros)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
