name       : libdrm
version    : 2.4.96
release    : 26
source     :
    - https://dri.freedesktop.org/libdrm/libdrm-2.4.96.tar.bz2 : 0d561acf7bb4cc59dc82415100e6c1a44860e8c380e00f9592923e3cd08db393
license    : MIT
component  : xorg.display
summary    : Direct Rendering Manager API + Library
description: |
    libdrm provides core library routines for the X Window System to directly interface with video hardware using the Linux kernel's Direct Rendering Manager (DRM).
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(pciaccess)
    - pkgconfig(pciaccess)
    - pkgconfig(xorg-macros)
setup      : |
    # %patch -p1 < $pkgfiles/0001-xf86drm-fallback-to-normal-path-when-realpath-fails.patch
    # sed -e /pthread-stubs/d -i configure.ac
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
# check      : |
#    %ninja_check
